### ISSUE TITLE
isValid returns False for valid personal ID numbers

### ISSUE THREAD

**Issue by denizdogan** [ahstro/elm-luhn#2]
The following renders "invalid" with this supposedly valid (but faked) personal ID number 195508316220:

```elm
view : Model -> Html Msg
view model =
    div []
        [ img [ src "/logo.svg" ] []
        , h1 [] [ text "Your Elm App is working!" ]
        , text <|
            if Luhn.isValid "195508316220" then
                "valid"

            else
                "invalid"
        ]
```

I tried looking at the source code to figure out where the problem could stem from, but I haven't found anything obvious.

**Comment by denizdogan** [comment]
Derp, it's the first two digits that should not be part of it, sorry for the noise.

**Comment by ahstro** [comment]
No worries 😊

That looks like a Swedish personal number, in which case you might want to check out [this lib](https://package.elm-lang.org/packages/niho/personal-number/latest/). I also had [a lib](https://github.com/ahstro/elm-ssn-validation) doing that, which relied on this package, but it's not updated to 0.19 yet, and I don't want to clutter the package repo if one already exists.

**Comment by denizdogan** [comment]
@ahstro Good to know, thank you!
